name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_URI: mongodb://m001-student:m001-mongodb-basics@sandbox-shard-00-00.hm81p.mongodb.net:27017,sandbox-shard-00-01.hm81p.mongodb.net:27017,sandbox-shard-00-02.hm81p.mongodb.net:27017/education?ssl=true&replicaSet=atlas-10d25v-shard-0&authSource=admin&retryWrites=true&w=majority
        file_name: .env
        fail_on_empty: false
